### ISSUE TITLE
Problem with Unity integration

### ISSUE THREAD

**Issue by dangost** [unminednet/Unmined.Minecraft.Nbt#1]
I'm trying to install this library in Unity 2021. I got an errors with dotnet versions.
When I tried to build library for netstandart2.1 i've got a lot of problems such as non-existed methods in BinaryPrimitives std class and language errors. Can you help me?

**Comment by megazyz** [comment]
Hello, 
This library uses runtime features that are not available in netstandard 2.1. Some of the compatibility issues can be fixed using polyfills, some are not. You have to rewrite some functions to make this work on netstandard. 
I don't plan to implement netstandard support in the near future, because I don't have time.
There are other NBT libraries on GitHub, some of them supports netstandard.
